import TanstackProvider from '@/componentes/providers/TanstackProvider'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import Footer from '../componentes/layout/Footer'
import Navbar from '../componentes/layout/Navbar'
import './globals.css'

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={openSans.className}>
        <TanstackProvider>
          <Navbar />
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  )
}
